-- CLINIC (진료) 중심 진료/의사 파트 테이블 (접수 제외, Oracle)

CREATE TABLE CLINIC (
    CLINIC_ID       NUMBER(19)     NOT NULL,
    RECEPTION_ID    NUMBER(19)      NULL,
    CLINIC_TYPE     VARCHAR2(20)   NULL,
    CLINIC_STATUS   VARCHAR2(20)   NULL,
    CLINIC_AT       TIMESTAMP      NULL,
    DOCTOR_ID       NUMBER(19)     NULL,
    CREATED_AT      TIMESTAMP      NULL,
    UPDATED_AT      TIMESTAMP      NULL,
    CONSTRAINT PK_CLINIC PRIMARY KEY (CLINIC_ID)
);

CREATE TABLE DOCTOR_NOTE (
    DOCTOR_NOTE_ID   NUMBER(19)     NOT NULL,
    CLINIC_ID        NUMBER(19)     NOT NULL,
    DOCTOR_ID        NUMBER(19)     NULL,
    WRITEN_AT        TIMESTAMP      NULL,
    STATUS           VARCHAR2(20)  NULL,
    SIGNED_AT        TIMESTAMP      NULL,
    CHIEF_COMPLAINT  VARCHAR2(1000) NULL,
    PRESENT_ILLNESS  CLOB          NULL,
    ASSESSMENT       CLOB          NULL,
    TREATMENT        CLOB          NULL,
    MAIN_DX_CODE     VARCHAR2(30)  NULL,
    MAIN_DX_NAME     VARCHAR2(200) NULL,
    CONSTRAINT PK_DOCTOR_NOTE PRIMARY KEY (DOCTOR_NOTE_ID),
    CONSTRAINT FK_DOCTOR_NOTE_CLINIC FOREIGN KEY (CLINIC_ID) REFERENCES CLINIC (CLINIC_ID)
);

CREATE TABLE DIAGNOSIS (
    DIAGNOSIS_ID   NUMBER(19)     NOT NULL,
    CLINIC_ID      NUMBER(19)     NOT NULL,
    DISEASE_CODE   VARCHAR2(30)  NULL,
    DISEASE_NAME   VARCHAR2(200) NULL,
    MAIN_YN        CHAR(1)       NULL,
    CREATED_AT     TIMESTAMP     NULL,
    UPDATED_AT     TIMESTAMP     NULL,
    CONSTRAINT PK_DIAGNOSIS PRIMARY KEY (DIAGNOSIS_ID),
    CONSTRAINT FK_DIAGNOSIS_CLINIC FOREIGN KEY (CLINIC_ID) REFERENCES CLINIC (CLINIC_ID)
);

CREATE TABLE ORDERS (
    ORDER_ID            NUMBER(19)    NOT NULL,
    CLINIC_ID            NUMBER(19)    NOT NULL,
    REQUESTED_AT         TIMESTAMP     NULL,
    ORDER_TYPE           VARCHAR2(50) NULL,
    ORDER_STATUS         VARCHAR2(20) NULL,
    REQUESTED_DOCTOR_ID  NUMBER(19)   NULL,
    CREATED_AT           TIMESTAMP    NULL,
    UPDATED_AT           TIMESTAMP    NULL,
    CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_ID),
    CONSTRAINT FK_ORDERS_CLINIC FOREIGN KEY (CLINIC_ID) REFERENCES CLINIC (CLINIC_ID)
);

CREATE TABLE ORDER_ITEM (
    ORDER_ITEM_ID  NUMBER(19)     NOT NULL,
    ORDER_ID       NUMBER(19)    NOT NULL,
    ITEM_CODE      VARCHAR2(50)  NULL,
    ITEM_CATEGORY  VARCHAR2(20)  NULL,
    ITEM_NAME      VARCHAR2(200) NULL,
    QTY            NUMBER(10,2)  NULL,
    DOSE           NUMBER(10,2)  NULL,
    UNIT           CHAR(18)      NULL,
    INSTRUCTION    VARCHAR2(1000) NULL,
    STATUS         VARCHAR2(20)  NULL,
    CREATED_AT     TIMESTAMP     NULL,
    CONSTRAINT PK_ORDER_ITEM PRIMARY KEY (ORDER_ITEM_ID),
    CONSTRAINT FK_ORDER_ITEM_ORDERS FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID)
);

CREATE TABLE PROCEDURE_RESULT (
    PROCEDURE_RESULT_ID  NUMBER(19)  NOT NULL,
    ORDER_ITEM_ID        NUMBER(19)  NOT NULL,
    STATUS               VARCHAR2(20) NULL,
    PERFORMED_AT         TIMESTAMP   NULL,
    PERFORMER_ID         NUMBER(19)  NULL,
    CONTENT              CLOB       NULL,
    CONSTRAINT PK_PROCEDURE_RESULT PRIMARY KEY (PROCEDURE_RESULT_ID),
    CONSTRAINT FK_PROCEDURE_RESULT_ORDER_ITEM FOREIGN KEY (ORDER_ITEM_ID) REFERENCES ORDER_ITEM (ORDER_ITEM_ID)
);

CREATE SEQUENCE SEQ_CLINIC START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DOCTOR_NOTE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DIAGNOSIS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ORDERS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ORDER_ITEM START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PROCEDURE_RESULT START WITH 1 INCREMENT BY 1 NOCACHE;
