INSERT INTO MENU (MENU_ID, PARENT_ID, CODE, NAME, PATH, ICON, SORT_ORDER, IS_ACTIVE, CREATED_AT, UPDATED_AT)
VALUES (SEQ_MENU.NEXTVAL, NULL, 'CHART', '차트', '/doctor', 'MedicalServices', 2, 1, SYSTIMESTAMP, SYSTIMESTAMP);
