-- CLINIC → CLINICAL 테이블/컬럼/시퀀스 이름 변경 (Oracle)
-- 실행 전 백업 권장. FK 제거 후 테이블·컬럼·제약·시퀀스 이름 변경.

ALTER TABLE DOCTOR_NOTE DROP CONSTRAINT FK_DOCTOR_NOTE_CLINIC;
ALTER TABLE DIAGNOSIS DROP CONSTRAINT FK_DIAGNOSIS_CLINIC;
ALTER TABLE ORDERS DROP CONSTRAINT FK_ORDERS_CLINIC;

RENAME CLINIC TO CLINICAL;

ALTER TABLE CLINICAL RENAME COLUMN CLINIC_ID TO CLINICAL_ID;
ALTER TABLE CLINICAL RENAME COLUMN CLINIC_TYPE TO CLINICAL_TYPE;
ALTER TABLE CLINICAL RENAME COLUMN CLINIC_STATUS TO CLINICAL_STATUS;
ALTER TABLE CLINICAL RENAME COLUMN CLINIC_AT TO CLINICAL_AT;

ALTER TABLE CLINICAL RENAME CONSTRAINT PK_CLINIC TO PK_CLINICAL;

ALTER TABLE DOCTOR_NOTE RENAME COLUMN CLINIC_ID TO CLINICAL_ID;
ALTER TABLE DOCTOR_NOTE ADD CONSTRAINT FK_DOCTOR_NOTE_CLINICAL
  FOREIGN KEY (CLINICAL_ID) REFERENCES CLINICAL (CLINICAL_ID);

ALTER TABLE DIAGNOSIS RENAME COLUMN CLINIC_ID TO CLINICAL_ID;
ALTER TABLE DIAGNOSIS ADD CONSTRAINT FK_DIAGNOSIS_CLINICAL
  FOREIGN KEY (CLINICAL_ID) REFERENCES CLINICAL (CLINICAL_ID);

ALTER TABLE ORDERS RENAME COLUMN CLINIC_ID TO CLINICAL_ID;
ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDERS_CLINICAL
  FOREIGN KEY (CLINICAL_ID) REFERENCES CLINICAL (CLINICAL_ID);

RENAME SEQ_CLINIC TO SEQ_CLINICAL;
